
// swift-tools-version: 5.10
// The swift-tools-version declares the minimum version of Swift required to build this package.
// =================================================================
// || Do not edit! This file is generated by node/zipFramework.js ||
// =================================================================

import PackageDescription

let package = Package(
  name: "MicroMaxOnAppleSilicon",
  platforms: [.iOS(.v14), .macOS(.v13), .visionOS(.v1)],
  products: [
    // Products define the executables and libraries a package produces, making them visible to other packages.
    .library(
      name: "MicroMaxOnAppleSilicon",
      targets: ["MicroMaxCBridge", "MicroMaxCppBridge", "MicroMaxObjCBridge", "MicroMaxOnAppleSilicon"]
    ),
  ],
  dependencies: [
    .package(url: "https://github.com/mesqueeb/Asyncify", from: "0.0.3"),
  ],
  targets: [
    .target(
      name: "MicroMaxCBridge",
      path: "MicroMaxOnAppleSilicon/CBridge"
    ),
    .target(
      name: "MicroMaxCppBridge",
      dependencies: ["MicroMaxCBridge"],
      path: "MicroMaxOnAppleSilicon/CppBridge"
    ),
    .target(
      name: "MicroMaxObjCBridge",
      dependencies: ["MicroMaxCppBridge"],
      path: "MicroMaxOnAppleSilicon/ObjCBridge",
      resources: [.copy("fmax.ini")],
      publicHeadersPath: "include"
    ),
    .target(
      name: "MicroMaxOnAppleSilicon",
      dependencies: ["Asyncify", "MicroMaxObjCBridge"],
      path: "MicroMaxOnAppleSilicon/SwiftBridge"
    ),
    .testTarget(
      name: "MicroMaxOnAppleSiliconTests",
      dependencies: ["MicroMaxCBridge", "MicroMaxCppBridge", "MicroMaxObjCBridge", "MicroMaxOnAppleSilicon"],
      resources: [.copy("fmax.ini")]
    ),
  ],
  cLanguageStandard: .gnu17,
  cxxLanguageStandard: .cxx20
)
